paths:
  /api/products/:
    # Obtener listado general de productos.
    get:
      summary: Obtener listado general de productos.
      tags:
        - Productos
      responses:
        "200":
          description: El listado general de productos fue obtenido exitosamente.
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Products"
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.
    # Agregar un nuevo producto.
    post:
      summary: Agregar un nuevo producto.
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/newProduct"
      responses:
        "200":
          description: El producto fue agregado exitosamente.
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.
  /api/products/{pid}:
    # Obtener detalle de producto específico.
    get:
      summary: Obtener detalle de producto específico.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El parámetro PID es el identificador del producto.
          schema:
            $type: string
      responses:
        "200":
          description: El detalle de producto específico fue obtenido exitosamente.
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor. 
    # Modificar detalle de producto específico.
    put:
      summary: Modificar detalle de producto específico.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El parámetro PID es el identificador del producto.
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: El detalle del producto específico fue modificado exitosamente.
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.
    # Eliminar producto específico.
    delete:
      summary: Eliminar producto específico.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El parámetro PID es el identificador del producto.
          schema:
            $type: string
      responses:
        "200":
          description: El producto específico fue eliminado exitosamente.
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.

components:
# RESPUESTAS
  schemas:
    # Respuesta Productos
    Products:
      type: object
      properties:
        status:
          type: string
          description: Estado de respuesta ante la solicitud.
          example: Success
        payload:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                description: Identificador del producto, autogenerado por la base de datos.
              title:
                type: string
                description: Título del producto.
              description:
                type: string
                description: Descripción del producto.
              code:
                type: string
                description: Código del producto, generado manualmente.
              price:
                type: number
                description: Precio del producto.
              status:
                type: string
                description: Estado del producto.
              stock:
                type: boolean
                description: Stock del producto.
              category:
                type: string
                description: Categoría del producto.
              thumbnails:
                type: array
                description: Miniaturas del producto.
              __v:
                type: number
                description: Versión del documento.
            example:
              - _id: 642f4e61ad40756bbf17ed9d
                title: title 01
                description: description 01
                code: abc01
                price: 1001
                status: true
                stock: 11
                category: cat01
                thumbnails: []
                __v: 0
              - _id: 642f4e82ad40756bbf17ed9f
                title: title 02
                description: description 02
                code: abc02
                price: 1002
                status: true
                stock: 12
                category: cat02
                thumbnails: []
                __v: 0
    # Respuesta Producto
    Product:
      type: object
      properties:
        status:
          type: string
          description: Estado de respuesta ante la solicitud.
          example: Success
        payload:
          type: object
          properties:
            _id:
              type: string
              description: Identificador del producto, autogenerado por la base de datos.
            title:
              type: string
              description: Título del producto.
            description:
              type: string
              description: Descripción del producto.
            code:
              type: string
              description: Código del producto, generado manualmente.
            price:
              type: number
              description: Precio del producto.
            status:
              type: string
              description: Estado del producto.
            stock:
              type: boolean
              description: Stock del producto.
            category:
              type: string
              description: Categoría del producto.
            thumbnails:
              type: array
              description: Miniaturas del producto.
            __v:
              type: number
              description: Versión del documento.
          example:
              _id: 642f4e61ad40756bbf17ed9d
              title: title 01
              description: description 01
              code: abc01
              price: 1001
              status: true
              stock: 11
              category: cat01
              thumbnails: []
              __v: 0
# CONSULTAS
  requestBodies:
    # Body Nuevo Producto
    newProduct:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre del usuario.
        last_name:
          type: string
          description: Apellido del usuario.
        email:
          type: string
          description: Correo del usuario, campo único.
        password:
          type: string
          description: Contraseña del usuario.
      example:
        first_name: pepe
        last_name: suarez
        email: pepe@gmail.com
        password: 1234
    # Body Modificar Producto
    updateProduct:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre del usuario.
        last_name:
          type: string
          description: Apellido del usuario.
        email:
          type: string
          description: Correo del usuario, campo único.
        password:
          type: string
          description: Contraseña del usuario.
      example:
        first_name: pepe
        last_name: suarez
        email: pepe@gmail.com
        password: 1234